# Generated by Django 4.0.2 on 2022-06-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_timestamp_alter_profile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
